In [94]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

# Load the dataset
url = '/content/Housing.csv'
data = pd.read_csv(url)
data.head()

# Preprocess the data
data.replace({'yes': 1, 'no': 0, 'furnished': 1, 'unfurnished': 0, 'semi-furnished': 2}, inplace=True)
X = data.drop('price', axis=1).values
print(X[:20])
y = data['price'].values
print(y[:20])
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# Scale the data using StandardScaler
scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

# Train the model using Perceptron algorithm
perceptron = Perceptron(max_iter=200000, eta0=0.01, random_state=0)
perceptron.fit(X_train_std, y_train)

# Make predictions on the testing set
y_pred = perceptron.predict(X_test_std)
print(y_pred[:20])
print(y_test[:20])
# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', round(accuracy, 2))


[[ 7420     4     2     3     1     0     0     0     1     2     1     1]
 [ 8960     4     4     4     1     0     0     0     1     3     0     1]
 [ 9960     3     2     2     1     0     1     0     0     2     1     2]
 [ 7500     4     2     2     1     0     1     0     1     3     1     1]
 [ 7420     4     1     2     1     1     1     0     1     2     0     1]
 [ 7500     3     3     1     1     0     1     0     1     2     1     2]
 [ 8580     4     3     4     1     0     0     0     1     2     1     2]
 [16200     5     3     2     1     0     0     0     0     0     0     0]
 [ 8100     4     1     2     1     1     1     0     1     2     1     1]
 [ 5750     3     2     4     1     1     0     0     1     1     1     0]
 [13200     3     1     2     1     0     1     0     1     2     1     1]
 [ 6000     4     3     2     1     1     1     1     0     2     0     2]
 [ 6550     4     2     2     1     0     0     0     1     1     1     2]
 [ 3500     4     2     2